import io
import csv
from typing import Dict, Any
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

class ReportGenerator:
    @classmethod
    def generate_pdf_report(cls, analysis_data: Dict[str, Any], candidate_name: str = "Candidate") -> bytes:
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            rightMargin=36,
            leftMargin=36,
            topMargin=36,
            bottomMargin=36
        )
        
        styles = getSampleStyleSheet()
        
        title_style = ParagraphStyle(
            'DocTitle',
            parent=styles['Heading1'],
            fontSize=22,
            leading=26,
            textColor=colors.HexColor('#1E293B'),
            fontName='Helvetica-Bold'
        )
        
        subtitle_style = ParagraphStyle(
            'DocSubtitle',
            parent=styles['Normal'],
            fontSize=11,
            leading=14,
            textColor=colors.HexColor('#64748B'),
            fontName='Helvetica'
        )
        
        heading2_style = ParagraphStyle(
            'Heading2Custom',
            parent=styles['Heading2'],
            fontSize=14,
            leading=18,
            textColor=colors.HexColor('#0F172A'),
            fontName='Helvetica-Bold',
            spaceBefore=12,
            spaceAfter=6
        )
        
        body_style = ParagraphStyle(
            'BodyCustom',
            parent=styles['Normal'],
            fontSize=10,
            leading=14,
            textColor=colors.HexColor('#334155'),
            fontName='Helvetica'
        )
        
        bullet_style = ParagraphStyle(
            'BulletCustom',
            parent=body_style,
            leftIndent=15,
            firstLineIndent=-10,
            spaceAfter=4
        )

        elements = []
        
        # Title Header
        elements.append(Paragraph(f"AI Resume Analysis Report", title_style))
        job_title = analysis_data.get("job_title") or "General Role Audit"
        elements.append(Paragraph(f"Candidate: <b>{candidate_name}</b> | Target Role: <b>{job_title}</b> | Generated by AI Resume Analyzer", subtitle_style))
        elements.append(Spacer(1, 10))
        elements.append(HRFlowable(width="100%", thickness=1.5, color=colors.HexColor('#6366F1'), spaceBefore=5, spaceAfter=15))
        
        # Executive Score Cards Table
        overall = analysis_data.get("overall_score", 0.0)
        ats = analysis_data.get("ats_score", 0.0)
        formatting = analysis_data.get("formatting_score", 0.0)
        skill_score = analysis_data.get("skill_match_score", 0.0)
        
        score_data = [
            ["Overall Score", "ATS Score", "Formatting Score", "Skill Score"],
            [f"{overall}%", f"{ats}%", f"{formatting}%", f"{skill_score}%"]
        ]
        
        score_table = Table(score_data, colWidths=[130, 130, 130, 130])
        score_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#4F46E5')),
            ('TEXTCOLOR', (0,0), (-1,0), colors.white),
            ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
            ('FONTSIZE', (0,0), (-1,0), 10),
            ('ALIGN', (0,0), (-1,-1), 'CENTER'),
            ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
            ('BACKGROUND', (0,1), (-1,1), colors.HexColor('#F8FAFC')),
            ('TEXTCOLOR', (0,1), (-1,1), colors.HexColor('#0F172A')),
            ('FONTNAME', (0,1), (-1,1), 'Helvetica-Bold'),
            ('FONTSIZE', (0,1), (-1,1), 16),
            ('BOTTOMPADDING', (0,0), (-1,-1), 8),
            ('TOPPADDING', (0,0), (-1,-1), 8),
            ('GRID', (0,0), (-1,-1), 1, colors.HexColor('#E2E8F0')),
        ]))
        elements.append(score_table)
        elements.append(Spacer(1, 15))
        
        # Detailed Score Breakdown Table
        elements.append(Paragraph("Score Breakdown Audit", heading2_style))
        breakdown_data = [
            ["Metric Category", "Score", "Evaluation Rating"],
            ["Readability Index", f"{analysis_data.get('readability_score', 0.0)}%", "Optimal Reading Ease"],
            ["Keyword Match Density", f"{analysis_data.get('keyword_match_score', 0.0)}%", "Target Industry Alignment"],
            ["Experience Impact Score", f"{analysis_data.get('experience_score', 0.0)}%", "Action Verbs & Achievements"],
            ["Education Completeness", f"{analysis_data.get('education_score', 0.0)}%", "Academic Qualification Match"],
            ["Project Portfolios", f"{analysis_data.get('project_score', 0.0)}%", "Hands-on Technical Proof"]
        ]
        breakdown_table = Table(breakdown_data, colWidths=[200, 100, 220])
        breakdown_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#F1F5F9')),
            ('TEXTCOLOR', (0,0), (-1,0), colors.HexColor('#334155')),
            ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
            ('FONTSIZE', (0,0), (-1,0), 9),
            ('BOTTOMPADDING', (0,0), (-1,-1), 6),
            ('TOPPADDING', (0,0), (-1,-1), 6),
            ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#CBD5E1')),
        ]))
        elements.append(breakdown_table)
        elements.append(Spacer(1, 15))
        
        # Skill Analysis Section
        elements.append(Paragraph("Skill Matrix & Gap Analysis", heading2_style))
        matched = ", ".join(analysis_data.get("matched_skills", [])) or "None identified"
        missing = ", ".join(analysis_data.get("missing_skills", [])) or "None identified"
        recommended = ", ".join(analysis_data.get("recommended_skills", [])) or "None identified"
        
        elements.append(Paragraph(f"<b>Matched Skills:</b> {matched}", body_style))
        elements.append(Spacer(1, 4))
        elements.append(Paragraph(f"<b>Missing Target Skills:</b> <font color='#EF4444'>{missing}</font>", body_style))
        elements.append(Spacer(1, 4))
        elements.append(Paragraph(f"<b>Recommended Skill Additions:</b> <font color='#6366F1'>{recommended}</font>", body_style))
        elements.append(Spacer(1, 15))
        
        # Actionable AI Recommendations Section
        elements.append(Paragraph("AI Recommendations & Action Plan", heading2_style))
        suggestions_dict = analysis_data.get("suggestions_json", {})
        
        if isinstance(suggestions_dict, dict):
            for category, sug_list in suggestions_dict.items():
                if sug_list:
                    cat_title = category.replace("_", " ").title()
                    elements.append(Paragraph(f"<b>{cat_title}:</b>", body_style))
                    for item in sug_list:
                        elements.append(Paragraph(f"• {item}", bullet_style))
                    elements.append(Spacer(1, 4))
                    
        doc.build(elements)
        buffer.seek(0)
        return buffer.getvalue()

    @classmethod
    def generate_csv_report(cls, analysis_data: Dict[str, Any], candidate_name: str = "Candidate") -> str:
        output = io.StringIO()
        writer = csv.writer(output)
        
        writer.writerow(["AI Resume Analysis Summary Report"])
        writer.writerow(["Candidate Name", candidate_name])
        writer.writerow(["Job Title", analysis_data.get("job_title", "N/A")])
        writer.writerow([])
        writer.writerow(["Metric", "Score"])
        writer.writerow(["Overall Score", analysis_data.get("overall_score")])
        writer.writerow(["ATS Score", analysis_data.get("ats_score")])
        writer.writerow(["Formatting Score", analysis_data.get("formatting_score")])
        writer.writerow(["Readability Score", analysis_data.get("readability_score")])
        writer.writerow(["Keyword Match Score", analysis_data.get("keyword_match_score")])
        writer.writerow(["Skill Match Score", analysis_data.get("skill_match_score")])
        writer.writerow(["Experience Score", analysis_data.get("experience_score")])
        writer.writerow(["Education Score", analysis_data.get("education_score")])
        writer.writerow(["Project Score", analysis_data.get("project_score")])
        writer.writerow([])
        writer.writerow(["Matched Skills", "|".join(analysis_data.get("matched_skills", []))])
        writer.writerow(["Missing Skills", "|".join(analysis_data.get("missing_skills", []))])
        writer.writerow(["Recommended Skills", "|".join(analysis_data.get("recommended_skills", []))])
        
        return output.getvalue()
